describe('foo', () => {
  it('has runtime error', () => {
    throw new Error('error thrown on purpose')
  })
})
